# Set the registry Yarn should use
npmRegistryServer: 'https://registry.yarnpkg.com'

# Enable strict package resolutions
enableStrictResolvers: true

# Configure global folder for package installations
globalFolder: '/usr/local/share/.yarn-global'

# Set the cache folder for Yarn
cacheFolder: './.yarn/cache'

# Prevent Yarn from automatically upgrading
updateChecks: false

# Enable offline mode to use previously cached packages
enableGlobalCache: true

# Yarn can automatically clean up unused packages
yarnClean: true

# Specify node-linker mode (e.g., node-modules, pnp)
nodeLinker: 'node-modules'

# Control version resolution from the lock file
preferDeferredVersions: true

# Disable legacy peer dependencies
legacyPeerDeps: false

# Enable fund reporting for open-source funding information
enableFund: true

# Ensure the `yarn.lock` file is formatted consistently
enableImmutableInstalls: true

# Disable security audits
enableAudit: false

# Set the audit level for reporting issues
auditLevel: 'info'

# Ignore lifecycle scripts defined in package.json
enableScripts: false

# Disable progress bars to reduce console output
enableProgressBars: false

# Prefer online fetching over offline cache
preferOffline: false
